api_key: "sesame"
endpoints:
- name: openrouter
  base_url: https://openrouter.ai/api
  api_key: ${OPENROUTER_API_KEY}

models:
- endpoint: openrouter
  model: openai/o3
  params:
    reasoning:
      effort: high
- endpoint: openrouter
  model: x-ai/grok-4
  params:
    reasoning:
      effort: high
- endpoint: openrouter
  model: deepseek/deepseek-r1-0528
- endpoint: openrouter
  model: moonshotai/kimi-k2
- endpoint: openrouter
  model: anthropic/claude-sonnet-4
  params:
    reasoning:
      max_tokens: 32768
- endpoint: openrouter
  model: google/gemini-2.5-pro
  params:
    reasoning:
      max_tokens: 32768

critic:
  endpoint: openrouter
  model: deepseek/deepseek-r1-0528
  temperature: 0.6
  strategy: merge
  # system_prompt: |
  #   You are an expert judge. Decide which answer (or combination) is best.
  # user_prompt: |
  #   Below are several candidate answers produced by different models.
  #   Choose the single best answer or merge them into one high-quality response.
  #   Return ONLY the final answer, with no additional commentary.
